fix search
NikolasGumenyuk/my-react-table-v2 pull request #5
Opened 2022-03-23 08:09 UTC by NikolasGumenyuk

done

2022-03-24 16:37 UTC, amarsik1 requested changes

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Body.js
> +  const { columns, item, search } = props;
export const Body = ({ columns, item, search  }) => {

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Body.js
> +    let field = text + '';
toString()

2022-03-24 16:37 UTC, amarsik1 commented on src/components/BasicTable.js
> +  const currentItem = searchResults.slice(firstPageIndex, lastPageIndex);
useMemo

2022-03-24 16:37 UTC, amarsik1 commented on src/components/BasicTable.js
>          onPageChange={(page) => setCurrentPage(page)}
onPageChange={setCurrentPage}

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Body.js
> +      dangerouslySetInnerHTML={{ __html: highlight(item[column.accessor]) }}
для чого це?

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Pagination.js
> +            key={pageNumber + "123"}
?

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Pagination.js
> +              &#8230;
{DOTS}

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Pagination.js
> +        key={-1}
?

2022-03-24 16:37 UTC, amarsik1 commented on src/components/Pagination.js
> +        key={-2}
?

2022-03-24 16:37 UTC, amarsik1 commented on src/components/usePagination.js
> +};
знаю, шо спізжено)

2022-03-24 16:38 UTC, amarsik1 commented on src/components/Pagination.js
> +              &#8230;
краще не іспользувать індекс в качестві ключа

2022-03-25 16:53 UTC, NikolasGumenyuk commented on src/components/Body.js
> +  const { columns, item, search } = props;
complete

2022-03-25 16:56 UTC, NikolasGumenyuk commented on src/components/BasicTable.js
>          onPageChange={(page) => setCurrentPage(page)}
complete

2022-03-25 17:15 UTC, NikolasGumenyuk commented on src/components/Body.js
> +    let field = text + '';
complete

2022-03-25 17:39 UTC, NikolasGumenyuk commented on src/components/BasicTable.js
> +  const currentItem = searchResults.slice(firstPageIndex, lastPageIndex);
complete, но хуйово

2022-03-25 17:42 UTC, NikolasGumenyuk commented on src/components/usePagination.js
> +};
ахахаха да ти прав, но я розібрався як воно работає

2022-03-25 18:25 UTC, NikolasGumenyuk commented on src/components/Pagination.js
> +              &#8230;
complete

2022-03-25 18:26 UTC, NikolasGumenyuk commented on src/components/Pagination.js
> +        key={-1}
complete

2022-03-25 18:26 UTC, NikolasGumenyuk commented on src/components/Pagination.js
> +        key={-2}
убрав

2022-03-25 18:27 UTC, NikolasGumenyuk commented on src/components/Pagination.js
> +            key={pageNumber + "123"}
komplete

2022-03-25 18:31 UTC, NikolasGumenyuk commented on src/components/Body.js
> +      dangerouslySetInnerHTML={{ __html: highlight(item[column.accessor]) }}
щоб добавить HTML

2022-03-27 13:23 UTC, merged